micronaut:
  application:
    name: javaServerless
datasources:
  default:
    dialect: MYSQL #This apparently does nothing
    url: jdbc:mysql://lambdatest.c4qoxufww9zr.us-west-2.rds.amazonaws.com/booksdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pfrank
    password: NotAPassword
    initial-size: 1
    max-active: 1
    max-idle: 1
    min-idle: 1

