micronaut:
  application:
    name: javaServerless
#This is replicated here because of issue https://github.com/micronaut-projects/micronaut-core/issues/3535
datasources:
  default:
    dialect: MYSQL #This apparently does nothing
    jdbc-url: jdbc:tc:mysql://localhost/booksdb?TC_DAEMON=true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test
    maximum-pool-size: 1
    minimum-idle: 1

